---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  with_first_found:
    - "{{ ansible-distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Ensure SVN packages are installed.
  package:
    name: "{{ svn_packages }}"
    state: present

- name: Ensure svn home folder exists.
  file:
    path: "{{ svn_repository_home }}"
    state: directory

- name: Copy subversion configuration file.
  template:
    src: subversion.conf.j2
    dest: "{{ svn_apache_conf_path }}/subversion.conf"
    owner: root
    group: root
  notify: restart apache

- name: Create a test repository.
  command: >
    svnadmin create testrepo
    chdir={{ svn_repository_home }}
    creates={{ svn_repository_home }}/testrepo/README.txt
  when: svn_create_test_repo

- name: Set ownership for svn directories.
  file:
    path: "{{ svn_repository_home }}"
    owner: "{{ svn_apache_user }}"
    group: "{{ svn_apache_user }}"
    recurse: true
  notify: restart apache

- name: Create init script for svnserve (Debian).
  copy:
    src: svnserve
    dest: /etc/init.d/svnserve
    mode: 0755
  when: ansible_os_family == 'Debian'
  register: svn_init_copy

# Workaround for bug https://github.com/ansible/ansible-modules-core/issues/915.
- name: Run systemd daemon_reload (Ubuntu/Debian workaround).
  systemd:
    name: svnserve
    daemon_reload: true
  when:
    - svn_init_copy.changed
    - ansible_os_family == 'Debian'
    - ansible_service_mgr == 'systemd'
  tags: ['skip_ansible_lint']

- name: Ensure SVN is started.
  service: name=svnserve state=started enabled=yes
