---
- name: Ensure SVN packages are installed.
  yum: "name={{ item }} state=installed"
  with_items:
    - mod_dav_svn
    - subversion
  when: ansible_os_family == 'RedHat'

- name: Ensure SVN packages are installed (Debian).
  apt: name={{ item }} state=installed
  with_items:
    - subversion
    - libapache2-svn
  when: ansible_os_family == 'Debian'

- name: Ensure svn home folder exists.
  file:
    path: "{{ svn_repository_home }}"
    state: directory

- name: Copy subversion configuration file.
  template:
    src: subversion.conf.j2
    dest: "{{ apache_conf_path }}/subversion.conf"
    owner: root
    group: root
  notify: restart apache

- name: Create a test repository.
  command: >
    svnadmin create testrepo
    chdir={{ svn_repository_home }}
    creates={{ svn_repository_home }}/testrepo/README.txt
  when: svn_create_test_repo

- name: Set ownership for svn directories.
  file:
    path: "{{ svn_repository_home }}"
    owner: apache
    group: apache
    recurse: yes
  notify: restart apache

# TODO: Is there any way to specify `--root {{ svn_repository_home }}`?
- name: Ensure svnserve service is started.
  service: name=svnserve state=started enabled=yes
